--- # Connection
- name: Install packages
  hosts: localhost
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 





  # Task block
  - name: Install packages
    ansible.builtin.package:
      name: 
      - wget
      - telnet
      - unzip
      - elinks
      state: present            #present       #latest