--- # Connection
- name: Install packages
  hosts: localhost
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 





  # Task block
  - name: Install wget
    ansible.builtin.package:
      name: wget
      state: absent            #present       #latest