--- # Connection
- name: Install mariadb
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user



    #Task Block
  - name: Install mariadb
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
    - mariad
