--- # Connection
- name: Install Wordpress
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user



    #Task Block
     - name: Start DB server
    systemd: 
      name: mariadb 
      state: restarted
      enabled: tru
