--- #Connection Block
- name: install packages
  host: all
  become: true
  become_method: sudo
  user: ec2-user
  tasks:


    #Task Block
   - name: Install telnet
     ansible.builtin.package:
        name: telnet
        state: present
